"""Regenerate the native clip table from the exported manifest."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[2]
m=json.loads((root/'art/characters/female_rifle/manifest.json').read_text())
(root/'Unreal/Source/ArmyPrototype/CharacterClips.h').write_text('// Generated by tools/character/generate_clips.py; source timing is 60 fps.\n#pragma once\nnamespace armyvisual {\nstruct Clip { const char* name; double duration, speed, phaseOffset; };\ninline constexpr Clip Clips[] = {\n'+''.join('{"%s", %.9f, %.9f, %.9f},\n'%(c['name'],c['duration'],c['reference_speed_mps'],c.get('phase_offset',0)) for c in m['clips'])+'};\ninline constexpr int ClipCount=sizeof(Clips)/sizeof(Clips[0]);\n}\n')
